# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_RustHE_wrappers", use_symbols = TRUE, package_name = "RustHE")

#' @docType package
#' @usage NULL
#' @useDynLib RustHE, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Add two interegers and return the result to R.
#' @export
add <- function(x, y) .Call(wrap__add, x, y)

